name: movie-review-sentiment
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.7.4
  - anyio=2.2.0
  - argon2-cffi=20.1.0
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=20.3.0
  - babel=2.9.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - blas=1.0
  - bleach=3.3.0
  - boto=2.49.0
  - boto3=1.17.35
  - botocore=1.20.36
  - brotlipy=0.7.0
  - bz2file=0.98
  - ca-certificates=2020.12.5
  - cachetools=4.2.1
  - catalogue=2.0.1
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - click=7.1.2
  - colorama=0.4.4
  - cryptography=3.4.6
  - cymem=2.0.5
  - cython-blis=0.7.4
  - dataclasses=0.8
  - decorator=4.4.2
  - defusedxml=0.7.1
  - entrypoints=0.3
  - google-api-core=1.25.1
  - google-auth=1.24.0
  - google-cloud-core=1.5.0
  - google-cloud-storage=1.19.0
  - google-crc32c=1.1.2
  - google-resumable-media=1.2.0
  - googleapis-common-protos=1.52.0
  - grpcio=1.36.1
  - icc_rt=2019.0.0
  - idna=2.10
  - importlib-metadata=3.7.3
  - intel-openmp=2020.2
  - ipykernel=5.5.0
  - ipython=7.21.0
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jinja2=2.11.3
  - jmespath=0.10.0
  - joblib=1.0.1
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter-packaging=0.7.12
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyter_server=1.5.1
  - jupyterlab=3.0.12
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.3.0
  - libcrc32c=1.1.1
  - libprotobuf=3.15.6
  - libsodium=1.0.18
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - msys2-conda-epoch=20160418
  - multidict=5.1.0
  - murmurhash=1.0.5
  - nbclassic=0.2.6
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - nest-asyncio=1.4.3
  - nltk=3.5
  - notebook=6.3.0
  - numpy=1.19.2
  - numpy-base=1.19.2
  - openssl=1.1.1j
  - packaging=20.9
  - pandas=1.2.3
  - pandoc=2.13
  - pandocfilters=1.4.2
  - parso=0.8.1
  - pathy=0.4.0
  - pickleshare=0.7.5
  - pip=21.0.1
  - preshed=3.0.5
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.18
  - protobuf=3.15.6
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pydantic=1.7.3
  - pygments=2.8.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.8
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2021.1
  - pywin32=300
  - pywinpty=0.5.7
  - pyzmq=22.0.3
  - regex=2021.3.17
  - requests=2.25.1
  - rsa=4.7.2
  - s3transfer=0.3.6
  - scikit-learn=0.23.2
  - scipy=1.6.1
  - send2trash=1.5.0
  - setuptools=52.0.0
  - shellingham=1.4.0
  - six=1.15.0
  - smart_open=2.2.1
  - sniffio=1.2.0
  - spacy=3.0.5
  - spacy-legacy=3.0.1
  - sqlite=3.35.2
  - srsly=2.4.0
  - terminado=0.9.3
  - testpath=0.4.4
  - thinc=8.0.2
  - threadpoolctl=2.1.0
  - tornado=6.1
  - tqdm=4.59.0
  - traitlets=5.0.5
  - typer=0.3.2
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - urllib3=1.26.4
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wasabi=0.8.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - yarl=1.6.3
  - zeromq=4.3.4
  - zipp=3.4.1
  - zlib=1.2.11
